# Generated by Django 4.2.15 on 2024-08-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Free", "Free Plan"),
                            ("Standard", "Standard Plan"),
                            ("Pro", "Pro Plan"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
